### ISSUE TITLE
[Bug] MlsGroup commit state isn't tracking staged commits correctly

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#1098]
Calling `propose_remove_member` on a non-existent member must not lead to a pending commit even if `commit_to_pending_proposals` is called afterwards. This appears to be only one symptom of fragile/broken state management.

See `test_proposal_validation.rs` for examples/details.

**Comment by augustocdias** [comment]
Can you assign me this issue?

**Comment by raphaelrobert** [comment]
@augustocdias You asked to be assigned here. Do you still intend to work on this or should I unassign you? The context is that it would be nice to close all issues marked with the 'bug' label before the 0.5 release and this is the last one.

**Comment by augustocdias** [comment]
I'm not gonna be working on it anymore. I had to interrupt because there was unanswered questions about corner cases in zulip: https://openmls.zulipchat.com/#narrow/stream/262730-general/topic/MlsGroup.20commit.20state.20isn't.20tracking.20staged.20commits.20corre.2E.2E.2E/near/325592896

In summary I personally don't think this should be handled as a bug. The function name could be better named and the documentation updated to let clear that an empty commit is not really empty.
