### ISSUE TITLE
Wrong serialization of AuthenticatedContent

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#1189]
TLS serialization of `AuthenticatedContent` appears to be wrong. The `wire_format` is missing in the type and it's not serialized as the first value in `FramedContentTbs`.

cc @kkohbrok

**Comment by kkohbrok** [comment]
Thanks for bringing this up. I'll take a look.

**Comment by kkohbrok** [comment]
Ah, I see what's going on. `FramedContentTbs` includes the version, but `AuthenticatedContent` doesn't. So it turns out my construction where we just include `FramedContentTbs` in `AuthenticatedContent` doesn't quite work without a manual serialization of `AuthenticatedContent`. I'll try to find a solution.
