### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#1374]
- [x] Make pre-release
- [ ] Release all dependencies (in this order):
  - [ ] traits
  - [ ] memory_keystore
  - [ ] basic_credential
  - [ ] evercrypt_backend
  - [ ] openmls_rust_crypto
  - [ ] openmls 
- [x] Make sure docs/book are up to date
- [ ] Write release docs

**Comment by raphaelrobert** [comment]
Aligning the version with the draft version doesn't make sense at this point. draft-20 will most likely be identical to the RFC as far as mechanics are concerned. 
Breaking changes are to be expected in versions below 1.0. As the changes become smaller, we will document them better in the CHANGELOG. 
Version 0.5 should be stable in terms of wire format (modulo bugs we find). After that, we should tackle the persistence format, so that the only breaking changes are API changes going forward.

**Comment by kkohbrok** [comment]
With a small delay OpenMLS 0.5 is now available on crates.io.
