### ISSUE TITLE
Unify how members are addressed in the managed API

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#213]
Form a previous discussion:

> It's tricky, because the amount of information varies:

    Adds: You need a full KeyPackage
    Remove: You just need an index
    Uniquely referencing a member: You need a Credential

 > We could refactor remove to accept a credential instead of an index, but the problem with Adds remains.

Alternatively we could reference clients by ID (TBD).

**Comment by kkohbrok** [comment]
Since the managed API will need to be initialized (since it needs to maintain state), we could require that it be initialized with a callback function that allows us to retrieve a `KeyPackage` remotely given an ID.

Uniquely referencing a member in a group is indeed a bit tricky. Having to use a Credential is a bit suboptimal, since Credentials are per-group. Ideally, MLS require IDs to be unique per group, i.e. it would be forbidden to add a member if a member with the same ID already exists.

**Comment by franziskuskiefer** [comment]
Blocked on https://mailarchive.ietf.org/arch/msg/mls/t6rJX4MbsNVYvt3qKdNBBw4OzAI/

**Comment by raphaelrobert** [comment]
This has been addressed with introducing the key package hash references recently.
