### ISSUE TITLE
Key store - key bound

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#656]
There have been concerns about the trait bound for the key values in the kay store.
Right now keys have to implement `Hash`.
https://github.com/openmls/openmls/blob/e9b65c651c56f101cff7d773717e261a3d74ef36/traits/src/key_store.rs#L25

One option would be to take a byte slice `k: &[u8]` instead. I think this would work. It might not improve performance though because the key might be a serialisation of a struct. But right now I think most keys can be cheaply converted to byte slices.

@OtaK thoughts or comments?

**Comment by OtaK** [comment]
Sorry in advance if this comment is a bit of a mess 😢 

## `K: std::hash::Hash` bound

As for replacing the `K: std::hash::Hash` bound, I think the proper would be to simply replace it with `K: AsRef<[u8]>`, allowing keys to be pretty much anything along the lines of raw byte slices/vecs, strings & string slices, numeric primitives -which all share the underlying representation of a `&[u8]`-, and that usually includes serialised formats as well since it's idiomatic that `serde` implementations can serialise to string **and** byte vecs/slices.

In short, while the `Hash` bound works very well for K/V stores of any kind backed by a `HashMap`, it becomes really restrictive when you're dealing with other kinds of stores, like persistent stores.

## Performance

On the performance standpoint, I think I haven't explained well during our call, but to put it better, in situations when we're not dealing with a memory map (i.e. `std::collections::HashMap` that itself has the very same trait bound on its key requirement), `std::hash::Hash` as a trait bound implies an inner usage of `std::collections::hash_map::DefaultHasher`, which wraps a SipHash-1-3 (cf. https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#2942) and that's something relatively more expensive to initialise & feed / finalize than passing a byte slice. 

Example, for an inner store that wants strings as keys, you'd have to do this and call it on every key lookup:

```rust
	#[inline(always)]
    fn key_to_hash<K: std::hash::Hash>(k: &K) -> String {
        use std::hash::Hasher as _;
        let mut s = std::collections::hash_map::DefaultHasher::new(); // SipHash-1-3 alloc & init
        k.hash(&mut s);
        format!("{:X}", s.finish()) // SipHash-1-3 finalization & dealloc + String format / alloc
    }
``` 

I don't know if that whole thing is really clear but there should be large performance increases for memory-based stores -by the means of reducing alloc/reallocs- and very low increases for I/O bound stores.

## Other

Then there's a theoretical concern about a rumored HashDOS on SipHash1-3 (which remains to be seen), Rust would maybe change their default hasher in the future, to use SipHash-2-4 for example, which would completely change the resulting hashes for the same key, for example: 

```
SipHash-1-3('foo'): 6A5CDCAD01C973FA
SipHash-2-4('foo'): DDE38BD48EAE7414
```

And that "silent" change would probably break most persistent stores, since keys would change by just upgrading the Rust version

**Comment by franziskuskiefer** [comment]
> but there should be large performance increases for memory-based stores

I doubt this because the identifiers will most likely be some value that needs to be serialised with a very similar performance. I'm happy to be convinced otherwise if you want to do a benchmark.

> that "silent" change would probably break most persistent stores

I hope that won't happen silently. But that's a better argument.

In any case, thanks for raising the concerns. We'll revisit the key store soon anyway and look at the key in this context as well.

**Comment by OtaK** [comment]
> I doubt this because the identifiers will most likely be some value that needs to be serialised with a very similar performance. I'm happy to be convinced otherwise if you want to do a benchmark.

Benchmark source here: https://github.com/OtaK/hash-key-benchmark

<details>
<summary>Results</summary>


#### Performed on:

```
OS: Funtoo Linux 1.4 x86_64
Kernel: 5.12.19-ck
Terminal: kitty
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz
GPU: NVIDIA GeForce RTX 3080
Memory: 11165MiB / 32087MiB
```

#### Results: ~5x difference

```
bytemap_read            time:   [2.5336 ns 2.5824 ns 2.6359 ns]
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

hashmap_read            time:   [10.526 ns 10.564 ns 10.600 ns]
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

```


</details>


Again, this kind of benchmark is absolutely pointless, it just measures that the SipHash-1-3 execution takes 7.5ns per key lookup. My point is that whatever your API consumer does (serialisation or whatever) outside of your library isn't your responsibility, but *forcing* your API consumer to do extra allocations in specific contexts (i.e. keystore *not* backed by a HashMap-like API) is imposing a constraint on the API consumer. 

Maybe this could make a difference in some particular situations, like a BIG post-offline catchup with millions of messages?



> I hope that won't happen silently. But that's a better argument.
> 
> In any case, thanks for raising the concerns. We'll revisit the key store soon anyway and look at the key in this context as well.

I hope so too, it's not usual that they'd do but it happens

Also, just for future reference if you need about idiomatic Rust API design guidelines in general: 

https://rust-lang.github.io/api-guidelines/about.html - Made by the core team

https://deterministic.space/elegant-apis-in-rust.html - A bit outdated but still completely valid


Happy holidays, cheers!

**Comment by raphaelrobert** [comment]
Thanks for the benchmarks!
On the topic of performance: I think the hashing performance can be neglected. The key store is meant to store ECDH and EdDSA/ECDSA keys. Whenever such a key is fetched, at least one operation is performed with the key (sometimes multiple operations). Such an operation takes ~50us, which is almost 4 orders of magnitude slower than hashing. I don't think the hashing will even be measurable.
Processing millions of messages will still take time, even with MLS. There are certainly a bunch of optimizations we can do, but that's something we should look at once the API is stable.
