### ISSUE TITLE
Enforce AEAD limits

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#925]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/684

**Description of the changes**
> Closes #664

**Comment by franziskuskiefer** [comment]
Related question: Should OpenMLS check for these limits or rely on the crypto provider?

**Comment by kkohbrok** [comment]
No particular opinion on who should keep track of this. But I'm wondering, where this is relevant. If I understand correctly, these limits are per key. And due to the sender ratchets, we use each symmetric key [exactly one time](https://www.ietf.org/archive/id/draft-ietf-mls-protocol-16.html#name-encryption-keys). Is MLS using AEAD in other places?

**Comment by raphaelrobert** [comment]
There's indeed no reason to believe we run into any of these limits, closing this.
