### ISSUE TITLE
[MLS Spec change] Move wire_format to a separate tagged-union structure MLSMessage #523

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#979]
**Description of the changes**
> The current use of wire_format is a bit weird to me: it is the first value of both MLSPlaintext and MLSCiphertext which allows the implementations to differentiate between them. Then it looks like it should be implemented as a regular tagged union, which is what this pull request does.
> 
> This does not imply any changes to existing implementations.
> 
> One thing that this pull-request changes is that MLSPlaintext is forced to have wire_format = mls_plaintext, but I don't see why it would have any other values in this case?

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/523

- [x] #958
- [x] #941
- [x] #881
- [x] #1134 
- [x] Fix the abstraction boundaries in the validation order
- [x] Update docs to reflect the new framing structure

Tracking required changes
- [x] Unambiguous signatures (#980)

**Comment by duesee** [comment]
I'll try the following: In order to minimize the changes that have to be done manually and to avoid confusing types in certain places, I'll first only do renames. The hope is that the "places" where the renamed types are used, i.e., when receiving a message, etc. are roughly similar.

Then, in order to put a final target in place we want to arrie at, I will then drop the current definitions and replace them with the MLS draft ones. Obviously things will break here. Then, I'll try to go to the diffs again and see what steps are necessary to arrive at the final code (or cry for help).

### Changes

#### Structs and Enums

* rename `MLSPlaintext` to `MLSMessageContent`
  * after rename: remove `wire_format` field.
  * after rename: remove `signature`, ... (copy from draft)

* rename `MLSPlaintextTBS` to `MLSPlaintext`
  * adjust

* rename `MLSCiphertext` to `MLSMessage`
  * after: adjust struct (copy from RFC)

* rename `MLSPlaintextTBM` to `MLSMessageContentTBM`
  * adjust

* rename `MLSPlaintextCommitContent` to `MLSMessageCommitContent`

* rename `MLSPlaintextCommitAuthData` to `MLSMessageCommitAuthData`

* `WireFormat` (add fields)

* add: `MLSMessageContentAuth`
* add: `MLSMessageAuth`
* add: `MLSMessageContentTBS`
* add: `MLSCiphertext`

tmp
